import Dropdown from "components/Dropdown";
import Input from "components/Input";
import InputMinMax from "components/InputMinMax";
import PhoneInput from "components/PhoneInput";
import Head from "next/head";
import { useEffect, useMemo, useState } from "react";

const mockData = [
  { id: 0, value: "1", label: "Select 1" },
  { id: 1, value: "2", label: "Select 2" },
  { id: 2, value: "3", label: "Select 3" },
];

export default function Home() {
  const [getvalue, setValue] = useState(0);
  const [getvalue1, setValue1] = useState(0);
  const [getvalue2, setValue2] = useState(0);
  const [getPrice, setPrice] = useState("");
  const [selectedValue, setSelectedValue] = useState([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Input
          getValue={getPrice}
          setValue={setPrice}
          wrapClassName="rounded-xl p-5 mb-5"
          onlyFieldRequired="Currency"
        />
         <Input
          password={true}
          passwordType={{color: "red", size: 16, wrapClassName: ""}}
          getValue={getvalue}
          setValue={setValue}
          maxLength={10}
          wrapClassName="rounded-xl p-5"
          leftEye={true}
          type={"password"}
          
        />
        <InputMinMax
          insideWrapClassName="rounded-xl p-5"
          getValueMin={getvalue1}
          setValueMin={setValue1}
          getValueMax={getvalue2}
          setValueMax={setValue2}
        />
        <PhoneInput /> */}
        <Dropdown
          placeHolder="Select..."
          options={mockData}
          selectedArrayValue={selectedValue}
          setSelectedValue={setSelectedValue}
          isMulti={true}
        />
      </main>
    </>
  );
}
